"""create users table

Revision ID: 463940bf725c
Revises: cc5f25142df1
Create Date: 2026-06-15 12:52:38.940598

"""
from collections.abc import Sequence

revision: str = '463940bf725c'
down_revision: str | None = 'cc5f25142df1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
